=== LoveTropics/LTDatapack/schemas/ltminigames/games.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "description": "String / Text Component of Game",
      "$ref": "./properties/text.schema.json"
    },
    "subtitle": {
      "$ref": "./properties/text.schema.json"
    },
    "icon": {
      "type": "string"
    },
    "intro_slideshow": {
      "type": "string"
    },
    "backend_id": {
      "type": "string"
    },
    "statistics_key": {
      "type": "string"
    },
    "minimum_participants": {
      "type": "integer",
      "minimum": 1
    },
    "maximum_participants": {
      "type": "integer"
    },
    "is_multi_game": {
      "type": "boolean"
    },
    "hide_from_list": {
      "type": "boolean"
    },
    "waiting": {
      "type": "object",
      "properties": {
        "map": {
          "$ref": "./properties/map.schema.json"
        },
        "behaviors": {
          "$ref": "./behaviors/behaviors.schema.json"
        }
      },
      "required": [
        "map",
        "behaviors"
      ]
    },
    "map": {
      "$ref": "./properties/map.schema.json"
    },
    "behaviors": {
      "$ref": "./behaviors/behaviors.schema.json"
    }
  },
  "required": [
    "name",
    "map",
    "behaviors"
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/survive_the_tide_3_high_tide.json
{
  "name": {"translate": "ltminigames.minigame.survive_the_tide_3"},
  "subtitle": "High Tide",
  "statistics_key": "survive_the_tide",
  "backend_id": "lt:survive_the_tide_3",

  "minimum_participants": 3,
  "maximum_participants": 32,
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:survive_the_tide_3"
  },
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "adventure",
      "join_late_with_role": "spectator"
    },
    {
      "type":  "lt:survive_the_tide/stt3_map",
      "tide": 190
    },
    "lt:survive_the_tide/stt3_phases",
    "lt:survive_the_tide/pets",
    "lt:survive_the_tide/ruleset",
    "lt:survive_the_tide/individuals_win_logic",
    "lt:survive_the_tide/weather_stt3",
    "lt:survive_the_tide/intro",
    "lt:survive_the_tide/stream_integrations",
    "lt:survive_the_tide/common"
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/survive_the_tide/1/voice_test.json
{
  "name": {
    "translate": "ltminigames.minigame.survive_the_tide_1",
    "color": "green",
    "extra": [
      " (Voice test)"
    ]
  },
  "icon": "ltminigames:minigames/survive_the_tide/icon",
  "minimum_participants": 3,
  "maximum_participants": 1000,
  "intro_slideshow": "lt:game/survive_the_tide/ffa_1",
  "waiting": {
    "map": {
      "type": "ltminigames:load_map",
      "load_from": "lt:games/waiting_lobby",
      "dimension_type": "tropicraft:tropics"
    },
    "behaviors": [
      {
        "type": "lt:common/waiting",
        "regions": {
          "spawn": "spawn"
        }
      }
    ]
  },
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:games/survive_the_tide/survive_the_tide_1",
    "dimension_type": "tropicraft:tropics"
  },
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "adventure",
      "join_late_with_role": "spectator",
      "backend_id": "lt:survive_the_tide_1",
      "statistics_key": "survive_the_tide"
    },
    "lt:survive_the_tide/1/map",
    "lt:survive_the_tide/1/phases",
    "lt:survive_the_tide/mode/ffa",
    "lt:survive_the_tide/1/weather",
    "lt:survive_the_tide/common",

    {
      "type": "ltgames_voice:voice_chat",
      "open_to_everyone": true
    },
    "lt:integrations/packages/bad_mic"
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/trash_dive.json
{
  "name": {
    "translate": "ltminigames.minigame.trash_dive",
    "color": "dark_green"
  },
  "minimum_participants": 1,
  "maximum_participants": 1000,
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:games/trash_dive/trash_dive",
    "dimension_type": "tropicraft:tropics"
  },
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "survival",
      "join_late_with_role": "participant",
      "allow_rejoin": true,
      "statistics_key": "trash_dive"
    },
    {
      "type": "ltminigames:position_players",
      "all": [
        "spawn"
      ]
    },
    {
      "type": "ltminigames:immediate_respawn",
      "role": "participant",
      "respawn_as": "spectator",
      "death_message": {
        "text": "☠ %message%",
        "color": "gray"
      },
      "drop_inventory": false
    },
    {
      "type": "ltminigames:place_trash",
      "positionData": "lt:maps/games/trash_dive/trash.bin",
      "centerY": 75,
      "range": 50,
      "density": 2
    },
    "ltminigames:trash_collection",
    {
      "type": "ltminigames:points_sidebar",
      "statistic": "trash_collected",
      "order": "max",
      "count": 5,
      "title": {
        "translate": "ltminigames.minigame.trash_dive.sidebar.title",
        "color": "blue",
        "bold": true
      },
      "header": [
        {
          "translate": "ltminigames.minigame.trash_dive.sidebar.instruction",
          "color": "green"
        },
        {
          "translate": "ltminigames.minigame.trash_dive.sidebar.collected",
          "color": "gray"
        },
        "",
        {
          "translate": "ltminigames.minigame.trash_dive.sidebar.top_players",
          "color": "green"
        }
      ]
    },
    {
      "type": "ltminigames:sum_statistic",
      "statistic": "trash_collected"
    },
    {
      "type": "ltminigames:place_by_statistic",
      "statistic": "points",
      "order": "max"
    },
    {
      "type": "ltminigames:events/game_over",
      "actions": [
        {
          "type": "ltminigames:display_leaderboard",
          "statistic": "trash_collected",
          "order": "max",
          "length": 5,
          "header": { "translate": "ltminigames.minigame.results" }
        }
      ],
      "target": "all_players"
    },
    {
      "type": "ltminigames:progression",
      "named_points": {
        "start": 0,
        "end": 300,
        "close": 310
      }
    },
    {
      "type": "ltminigames:scheduled_actions",
      "target": "all_players",
      "actions": {
        "end": "ltminigames:end_game",
        "close": "ltminigames:close_game"
      }
    },
    {
      "type": "ltminigames:countdown_effects",
      "target": "end",
      "sound": "minecraft:block.end_portal_frame.fill",
      "seconds": 5,
      "pitch": {
        "start": 1.25,
        "end": 0.25
      }
    },
    {
      "type": "ltminigames:phase_progress_bar",
      "entries": [
        {
          "period": {
            "start": "start",
            "end": "end"
          },
          "text": {
            "translate": "ltminigames.minigame.trash_dive",
            "color": "green"
          },
          "color": "green",
          "include_time": true,
          "reversed": true
        }
      ]
    },
    "ltminigames:disable_hunger",
    {
      "type": "ltminigames:set_role",
      "role": "participant",
      "actions": {
        "type": "ltminigames:add_equipment",
        "feet": "tropicraft:pink_scuba_flippers"
      }
    },
    {
      "type": "ltminigames:set_xp_to_statistic",
      "statistic": "trash_collected"
    },
    "lt:common/spectator",
    {
      "type": "lt:fixed_rewards",
      "coins": 10
    },
    "ltminigames:disable_throwing_items"
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/escape_race/main.json
{
  "name": {
    "translate": "ltminigames.minigame.escape_race",
    "color": "gold",
    "extra": [
      " ",
      {
        "translate": "ltminigames.minigame.teams_2",
        "color": "gold"
      }
    ]
  },
  "minimum_participants": 1,
  "maximum_participants": 6,
  "hide_from_list": true,
  "is_multi_game": true,
  "waiting": {
    "map": {
      "type": "ltminigames:load_map",
      "load_from": "lt:games/waiting_lobby",
      "dimension_type": "tropicraft:tropics"
    },
    "behaviors": [
      {
        "type": "lt:common/waiting",
        "regions": {
          "spawn": "spawn"
        }
      },
      {
        "type": "ltminigames:setup_teams",
        "teams": {
          "blue": {
            "name": {
              "translate": "ltminigames.minigame.teams.blue"
            },
            "dye": "blue",
            "assign_roles": ["river_race_blue"]
          },
          "red": {
            "name": {
              "translate": "ltminigames.minigame.teams.red"
            },
            "dye": "red",
            "assign_roles": ["river_race_red"]
          }
        }
      }
    ]
  },
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:games/escape_race/escape_race_warehouse",
    "dimension_type": "lt:raised_clouds"
  },
  "behaviors": "lt:escape_race/warehouse/main"
}

=== LoveTropics/LTDatapack/data/lt/games/levitation.json
{
  "name": {
    "translate": "ltminigames.minigame.levitation",
    "color": "dark_green"
  },
  "minimum_participants": 1,
  "maximum_participants": 1000,
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:games/levitation"
  },
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "adventure",
      "join_late_with_role": "spectator",
      "statistics_key": "levitation"
    },
    {
      "type": "ltminigames:position_players",
      "participants": "spawn",
      "spectators": "end"
    },
    {
      "type": "ltminigames:progression",
      "named_points": {
        "start": 0,
        "rise": 10
      }
    },
    {
      "type": "ltminigames:scheduled_actions",
      "actions": {
        "rise": {
          "type": "ltminigames:set_blocks",
          "replace": {
            "blocks": [
              "minecraft:light_blue_stained_glass"
            ]
          },
          "set": "minecraft:air",
          "region": "barrier"
        }
      }
    },
    {
      "type": "ltminigames:events",
      "events": {
        "player_participate": [
          {
            "type": "ltminigames:give_effect",
            "effects": [
              {
                "type": "minecraft:levitation",
                "seconds": 100000,
                "amplifier": 1,
                "particles": false,
                "show_icon": false
              }
            ]
          },
          {
            "type": "ltminigames:run_commands",
            "entity": "tag @s add levitation.yes"
          }
        ],
        "player_remove": {
          "type": "ltminigames:run_commands",
          "entity": "tag @s remove levitation.yes"
        }
      }
    },
    {
      "type": "ltminigames:phase_triggers/stop",
      "actions": {
        "type": "ltminigames:run_commands",
        "regions": {
          "end": [
            "kill @e[current_world\u003dtrue,type\u003dminecraft:fishing_bobber]"
          ]
        }
      }
    },
    {
      "type": "ltminigames:while_in_region",
      "regions": {
        "end": [
          {
            "type": "ltminigames:run_commands",
            "entity": [
              "tellraw @a[tag\u003dlevitation.yes] [{\"selector\":\"@s\",\"extra\":[{\"text\":\" has won the game!\"}]}]",
              "kill @e[current_world\u003dtrue,type\u003dminecraft:fishing_bobber]"
            ]
          },
          "ltminigames:close_game"
        ]
      },
      "interval": 5
    },
    {
      "type": "ltminigames:set_role",
      "role": "participant",
      "actions": {
        "type": "ltminigames:add_equipment",
        "items": [
          {
            "id": "minecraft:fishing_rod",
            "components": {
              "unbreakable": {},
              "ltextras:undroppable": {}
            }
          }
        ]
      }
    },
    "ltminigames:disable_hunger",
    {
      "type": "ltminigames:set_game_rules",
      "rules": {
        "minecraft:command_blocks_work": false,
        "minecraft:locator_bar": false,
        "minecraft:spawn_mobs": false,
        "minecraft:immediate_respawn": true,
        "minecraft:advance_weather": false,
        "minecraft:fall_damage": false,
        "minecraft:advance_time": false,
        "minecraft:show_advancement_messages": false
      }
    },
    {
      "type": "ltminigames:cancel_player_damage",
      "knockback": true
    },
    "ltminigames:immediate_respawn",
    "lt:common/spectator",
    {
      "type": "ltminigames:scheduled_actions",
      "target": "all_players",
      "actions": {
        "1": {
          "type": "ltminigames:send_message",
          "message": {
            "translate": "ltminigames.minigame.levitation.intro1",
            "color": "green",
            "italic": true
          }
        },
        "4": {
          "type": "ltminigames:send_message",
          "message": {
            "translate": "ltminigames.minigame.levitation.intro2",
            "color": "gray",
            "italic": true
          }
        }
      }
    },
    {
      "type": "lt:fixed_rewards",
      "coins": 5
    }
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/race_standard_21.json
{
  "name": {
    "translate": "ltminigames.minigame.turtle_race"
  },
  "subtitle": "Standard 2 Lap - LT21",
  "icon": "ltminigames:minigames/turtle_race/turtle_icon_1",
  "statistics_key": "race_standard_21",
  "backend_id": "lt:turtle_race",
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:turtle_race_21",
    "dimension_type": "tropicraft:tropics"
  },
  "waiting": {
    "map": {
      "type": "ltminigames:load_map",
      "load_from": "lt:waiting_lobby",
      "dimension_type": "tropicraft:tropics"
    },
    "behaviors": [
      {
        "type": "lt:common/waiting",
        "regions": {"spawn": "spawn"}
      }
    ]
  },
  "minimum_participants": 4,
  "maximum_participants": 1000,
  "behaviors": [
    {
      "type": "lt:turtle_race/standard",
      "track_point_count": 130,
      "lap_count": 2
    }
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/columns_of_chaos/ffa.json
{
  "name": {
    "translate": "ltminigames.minigame.columns_of_chaos",
    "color": "dark_green"
  },
  "minimum_participants": 1,
  "maximum_participants": 1000,
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:games/pillars_of_wealth"
  },
  "waiting": {
    "map": {
      "type": "ltminigames:load_map",
      "load_from": "lt:games/waiting_lobby",
      "dimension_type": "tropicraft:tropics"
    },
    "behaviors": [
      {
        "type": "lt:common/waiting",
        "regions": {
          "spawn": "spawn"
        }
      }
    ]
  },
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "survival",
      "join_late_with_role": "spectator",
      "statistics_key": "columns_of_chaos"
    },
    {
      "type": "lt:columns_of_chaos/common",
      "team_based": false
    },
    {
      "type": "lt:columns_of_chaos/phases",
      "total_seconds": 600
    }
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/forklift_racing/forklift_racing.json
{
  "name": {
    "translate": "Forklift Racing",
    "color": "dark_green"
  },
  "icon": "ltminigames:minigames/turtle_race/turtle_icon_1",
  "maximum_participants": 50,
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:forklift_race",
    "dimension_type": "tropicraft:tropics"
  },
  "behaviors": "lt:forklift_race/game"
}
