=== LoveTropics/LTDatapack/schemas/ltminigames/games.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "description": "String / Text Component of Game",
      "$ref": "./properties/text.schema.json"
    },
    "subtitle": {
      "$ref": "./properties/text.schema.json"
    },
    "icon": {
      "type": "string"
    },
    "intro_slideshow": {
      "type": "string"
    },
    "backend_id": {
      "type": "string"
    },
    "statistics_key": {
      "type": "string"
    },
    "minimum_participants": {
      "type": "integer",
      "minimum": 1
    },
    "maximum_participants": {
      "type": "integer"
    },
    "is_multi_game": {
      "type": "boolean"
    },
    "hide_from_list": {
      "type": "boolean"
    },
    "waiting": {
      "type": "object",
      "properties": {
        "map": {
          "$ref": "./properties/map.schema.json"
        },
        "behaviors": {
          "$ref": "./behaviors/behaviors.schema.json"
        }
      },
      "required": [
        "map",
        "behaviors"
      ]
    },
    "map": {
      "$ref": "./properties/map.schema.json"
    },
    "behaviors": {
      "$ref": "./behaviors/behaviors.schema.json"
    }
  },
  "required": [
    "name",
    "map",
    "behaviors"
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/survive_the_tide_3_low_tide.json
{
  "name": {"translate": "ltminigames.minigame.survive_the_tide_3"},
  "subtitle": "Low Tide",
  "statistics_key": "survive_the_tide",
  "backend_id": "lt:survive_the_tide_3",

  "minimum_participants": 3,
  "maximum_participants": 32,
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:survive_the_tide_3"
  },
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "adventure",
      "join_as_role": "spectator"
    },
    {
      "type":  "lt:survive_the_tide/stt3_map",
      "tide": 180
    },
    "lt:survive_the_tide/stt3_phases",
    "lt:survive_the_tide/pets",
    "lt:survive_the_tide/ruleset",
    "lt:survive_the_tide/individuals_win_logic",
    "lt:survive_the_tide/weather",
    "lt:survive_the_tide/intro",
    "lt:survive_the_tide/stream_integrations",
    "lt:survive_the_tide/common"
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/box_hunt.json
{
  "name": {
    "translate": "ltminigames.minigame.box_hunt",
    "color": "dark_green",
    "extra": [
      " ",
      {
        "translate": "ltminigames.minigame.teams_2",
        "color": "gold"
      }
    ]
  },
  "minimum_participants": 2,
  "maximum_participants": 1000,
  "waiting": {
    "map": {
      "type": "ltminigames:load_map",
      "load_from": "lt:games/waiting_lobby",
      "dimension_type": "tropicraft:tropics"
    },
    "behaviors": [
      {
        "type": "lt:common/waiting",
        "regions": {
          "spawn": "spawn"
        }
      },
      "lt:teams/hiders_seekers"
    ]
  },
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:games/box_hunt",
    "dimension_type": "tropicraft:tropics"
  },
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "adventure",
      "join_late_with_role": "spectator",
      "backend_id": "lt:box_hunt",
      "statistics_key": "box_hunt"
    },
    "ltminigames:teams",
    {
      "type": "ltminigames:position_players",
      "teams": {
        "hiders": [
          "boxes_spawn"
        ],
        "seekers": [
          "hunters_spawn"
        ]
      },
      "spectators": [
        "boxes_spawn"
      ]
    },
    {
      "type": "ltminigames:last_remaining_win_trigger",
      "last_team": true
    },
    {
      "type": "ltminigames:update_word_boxes_in_world",
      "block_entity_type": "ltextras:word_box"
    },
    "ltminigames:disable_hunger",
    "lt:box_hunt/equipment",
    "lt:box_hunt/actions",
    "lt:survive_the_tide/mode/teams/glow",
    "lt:common/spectator",
    {
      "type": "ltminigames:set_game_rules",
      "rules": {
        "minecraft:command_blocks_work": false,
        "minecraft:locator_bar": false,
        "minecraft:spawn_mobs": false,
        "minecraft:immediate_respawn": true,
        "minecraft:natural_health_regeneration": false,
        "minecraft:advance_weather": false,
        "minecraft:fall_damage": false,
        "minecraft:advance_time": false,
        "minecraft:show_advancement_messages": false
      }
    },
    {
      "type": "ltminigames:game_end_effects",
      "stop_delay": 200
    },
    "lt:common/announce_game_over",
    {
      "type": "lt:fixed_rewards",
      "coins": 5
    }
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/turtle_race.json
{
  "name": {"translate": "ltminigames.minigame.turtle_race"},
  "icon": "ltminigames:textures/gui/minigames/turtle_race/turtle_icon_1.png",

  "statistics_key": "turtle_race",
  "map": {
    "type": "ltminigames:inline",
    "dimension": "tropicraft:tropics"
  },
  "minimum_participants": 1,
  "maximum_participants": 10,
  "behaviors": [
    {
      "type": "ltminigames:set_game_types",
      "participant": "adventure",
      "spectator": "spectator"
    },
    {
      "type": "ltminigames:commands",
      "ready": "scoreboard players set Mode TRaceGlobal 1",
      "start": "function lt:minigames/turtle_race/begin",
      "player_join": "function lt:minigames/turtle_race/player/join",
      "cancel": "function lt:minigames/turtle_race/cancel"
    },
    "ltminigames:spectator_chase",
    {
      "type": "ltminigames:bind_objective_to_statistic",
      "objectives": {
        "placement": "TRacePlayerPlace",
        "total_time": "TRacePlayerS"
      }
    }
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/eruptive_spleef_teams.json
{
  "waiting": {
    "map": {
      "type": "ltminigames:load_map",
      "load_from": "lt:waiting_lobby",
      "dimension_type": "tropicraft:tropics"
    },
    "behaviors": [
      {
        "type": "lt:common/waiting",
        "regions": {
          "spawn": "spawn"
        }
      },
      "lt:teams/red_blue"
    ]
  },

  "name": {"translate": "ltminigames.minigame.eruptive_spleef_teams"},
  "statistics_key": "eruptive_spleef_teams",
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:eruptive_spleef"
  },
  "minimum_participants": 1,
  "maximum_participants": 1000,
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "adventure",
      "join_late_with_role": "spectator"
    },
    "ltminigames:teams",
    {
      "type": "ltminigames:position_players",
      "teams": {
        "blue": ["blue_spawn"],
        "red": ["red_spawn"]
      },
      "face_region": "center",
      "split_by_team": true,
      "all": "center",
      "spectators": ["center"]
    },
    "ltminigames:spectator_chase",
    {
      "type": "ltminigames:last_remaining_win_trigger",
      "last_team": true
    },
    "lt:eruptive_spleef/ruleset",
    "lt:eruptive_spleef/equipment",
    "lt:eruptive_spleef/lava",
    {
      "type": "ltminigames:game_end_effects",
      "stop_delay": 200
    },
    "lt:common/announce_game_over",
    "ltminigames:time_survived_tracker",
    {
      "type": "ltminigames:game_finish",
      "actions": {
        "type": "ltminigames:apply_to_player",
        "target": "all",
        "actions": {
          "type": "ltminigames:give_reward",
          "items": ["ltextras:tropicoin"],
          "statistic_binding": {
            "statistic": "time_survived",
            "multiplier": 0.2
          }
        }
      }
    }
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/block_party.json
{
  "name": {"translate": "ltminigames.minigame.block_party"},

  "statistics_key": "block_party",
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:block_party"
  },
  "minimum_participants": 1,
  "maximum_participants": 32,
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "adventure",
      "join_late_with_role": "spectator"
    },
   "ltminigames:last_remaining_win_trigger",
    {
      "type": "ltminigames:block_party",
      "floor": "blocks",
      "blocks": [
        "minecraft:red_mushroom_block",
        "minecraft:shroomlight",
        "ltextras:imposter_horn_coral_block",
        "minecraft:melon",
        "minecraft:warped_wart_block",
        "minecraft:blue_ice",
        "ltextras:imposter_tube_coral_block",
        "ltextras:imposter_bubble_coral_block",
        {
          "Name": "minecraft:cherry_leaves",
          "Properties": {
            "persistent": "true"
          }
        }
      ],
      "quad_size": 3,
      "max_time": 280,
      "time_decay_rounds": 10,
      "interval": 80,
      "knockback_after_round": 5
    },
    {
      "type": "ltminigames:set_game_rules",
      "rules": {
        "doDaylightCycle": "false",
        "doWeatherCycle": "false",
        "doMobSpawning": "false",
        "fallDamage": "false",
        "announceAdvancements": "false",
        "doImmediateRespawn": "true"
      }
    },
    "ltminigames:disable_hunger",
    "ltminigames:spectator_chase",
    "ltminigames:disable_throwing_items",
    "lt:common/announce_game_over",
    {
      "type": "ltminigames:game_finish",
      "actions": {
        "type": "ltminigames:apply_to_player",
        "target": "all",
        "actions": {
          "type": "ltminigames:give_reward",
          "items": ["ltextras:tropicoin"],
          "statistic_binding": {
            "statistic": "rounds_survived"
          }
        }
      }
    }
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/forklift_racing/crab_race.json
{
  "name": {
    "translate": "Crab Racing",
    "color": "dark_green"
  },
  "icon": "ltminigames:minigames/turtle_race/turtle_icon_1",
  "maximum_participants": 50,
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:games/mysty/racing/iceboat",
    "dimension_type": "tropicraft:tropics"
  },
  "behaviors": "lt:crab_race/game"
}

=== LoveTropics/LTDatapack/data/lt/games/escape_race/rooms/1.json
{
  "name": {
    "translate": "ltminigames.minigame.escape_race.room_1",
    "color": "dark_green"
  },
  "hide_from_list": true,
  "maximum_participants": 1000,
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:escape_race_room_1",
    "dimension_type": "lt:raised_clouds"
  },
  "waiting": {
    "map": {
      "type": "ltminigames:load_map",
      "load_from": "lt:waiting_lobby",
      "dimension_type": "tropicraft:tropics"
    },
    "behaviors": [
      {
        "type": "lt:common/waiting",
        "regions": {
          "spawn": "spawn"
        }
      },
      "lt:escape_race/one_team"
    ]
  },
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "adventure",
      "join_late_with_role": "spectator",
      "allow_rejoin": true
    },
    {
      "type": "lt:escape_race/rooms/1/common_1"
    }
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/block_party_teams.json
{
  "waiting": {
    "map": {
      "type": "ltminigames:load_map",
      "load_from": "lt:waiting_lobby",
      "dimension_type": "tropicraft:tropics"
    },
    "behaviors": [
      {
        "type": "lt:common/waiting",
        "regions": {
          "spawn": "spawn"
        }
      },
      "lt:teams/red_blue"
    ]
  },

  "name": {"translate": "ltminigames.minigame.block_party_teams"},
  "statistics_key": "block_party",
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:block_party_teams"
  },
  "minimum_participants": 1,
  "maximum_participants": 32,
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "adventure",
      "join_late_with_role": "spectator"
    },
    "ltminigames:teams",
    {
      "type": "ltminigames:last_remaining_win_trigger",
      "last_team": true
    },
    {
      "type": "ltminigames:block_party",
      "floor": "blocks",
      "blocks": [
        "minecraft:red_mushroom_block",
        "minecraft:shroomlight",
        "ltextras:imposter_horn_coral_block",
        "minecraft:melon",
        "minecraft:warped_wart_block",
        "minecraft:blue_ice",
        "ltextras:imposter_tube_coral_block",
        "ltextras:imposter_bubble_coral_block",
        {
          "Name": "minecraft:cherry_leaves",
          "Properties": {
            "persistent": "true"
          }
        }
      ],
      "quad_size": 3,
      "max_time": 280,
      "time_decay_rounds": 10,
      "interval": 80,
      "knockback_after_round": 5
    },
    {
      "type": "ltminigames:set_game_rules",
      "rules": {
        "doDaylightCycle": "false",
        "doWeatherCycle": "false",
        "doMobSpawning": "false",
        "fallDamage": "false",
        "announceAdvancements": "false",
        "doImmediateRespawn": "true"
      }
    },
    "ltminigames:disable_hunger",
    "ltminigames:spectator_chase",
    "ltminigames:disable_throwing_items",
    "lt:common/announce_game_over",
    {
      "type": "lt:fixed_rewards",
      "coins": 5
    }
  ]
}
