=== LoveTropics/LTDatapack/schemas/ltminigames/games.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "description": "String / Text Component of Game",
      "$ref": "./properties/text.schema.json"
    },
    "subtitle": {
      "$ref": "./properties/text.schema.json"
    },
    "icon": {
      "type": "string"
    },
    "intro_slideshow": {
      "type": "string"
    },
    "backend_id": {
      "type": "string"
    },
    "statistics_key": {
      "type": "string"
    },
    "minimum_participants": {
      "type": "integer",
      "minimum": 1
    },
    "maximum_participants": {
      "type": "integer"
    },
    "is_multi_game": {
      "type": "boolean"
    },
    "hide_from_list": {
      "type": "boolean"
    },
    "waiting": {
      "type": "object",
      "properties": {
        "map": {
          "$ref": "./properties/map.schema.json"
        },
        "behaviors": {
          "$ref": "./behaviors/behaviors.schema.json"
        }
      },
      "required": [
        "map",
        "behaviors"
      ]
    },
    "map": {
      "$ref": "./properties/map.schema.json"
    },
    "behaviors": {
      "$ref": "./behaviors/behaviors.schema.json"
    }
  },
  "required": [
    "name",
    "map",
    "behaviors"
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/survive_the_tide/3/high_tide_teams_3.json
{
  "name": {
    "translate": "ltminigames.minigame.survive_the_tide_3",
    "color": "blue",
    "extra": [
      " ",
      {
        "translate": "ltminigames.minigame.teams_3",
        "color": "dark_green"
      }
    ]
  },
  "subtitle": {
    "translate": "ltminigames.minigame.high",
    "color": "red"
  },
  "icon": "ltminigames:minigames/survive_the_tide/icon",
  "intro_slideshow": "lt:game/survive_the_tide/teams_3",
  "minimum_participants": 3,
  "maximum_participants": 1000,
  "waiting": {
    "map": {
      "type": "ltminigames:load_map",
      "load_from": "lt:games/waiting_lobby",
      "dimension_type": "tropicraft:tropics"
    },
    "behaviors": [
      {
        "type": "lt:common/waiting",
        "regions": {
          "spawn": "spawn"
        }
      },
      "lt:teams/red_blue_yellow"
    ]
  },
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:games/survive_the_tide/survive_the_tide_3",
    "dimension_type": "lt:raised_clouds"
  },
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "adventure",
      "join_late_with_role": "spectator",
      "backend_id": "lt:survive_the_tide_3_teams",
      "statistics_key": "survive_the_tide"
    },
    {
      "type": "lt:survive_the_tide/3/map",
      "tide": 190
    },
    "lt:survive_the_tide/3/phases",
    "lt:survive_the_tide/mode/teams",
    "lt:survive_the_tide/3/weather",
    "lt:survive_the_tide/common"
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/columns_of_chaos_teams_endless.json
{
  "waiting": {
    "map": {
      "type": "ltminigames:load_map",
      "load_from": "lt:waiting_lobby",
      "dimension_type": "tropicraft:tropics"
    },
    "behaviors": [
      {
        "type": "lt:common/waiting",
        "regions": {
          "spawn": "spawn"
        }
      },
      "lt:teams/red_blue"
    ]
  },

  "name": {"translate": "ltminigames.minigame.columns_of_chaos_teams_endless"},
  "statistics_key": "columns_of_chaos",
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:pillars_of_wealth"
  },
  "minimum_participants": 1,
  "maximum_participants": 30,
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "survival",
      "join_late_with_role": "spectator"
    },
    "ltminigames:teams",
    "lt:columns_of_chaos/common"
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/survive_the_tide/3/low_tide.json
{
  "name": {
    "translate": "ltminigames.minigame.survive_the_tide_3",
    "color": "blue"
  },
  "subtitle": {
    "translate": "ltminigames.minigame.low",
    "color": "red"
  },
  "icon": "ltminigames:minigames/survive_the_tide/icon",
  "intro_slideshow": "lt:game/survive_the_tide/ffa_3",
  "minimum_participants": 3,
  "maximum_participants": 1000,
  "waiting": {
    "map": {
      "type": "ltminigames:load_map",
      "load_from": "lt:games/waiting_lobby",
      "dimension_type": "tropicraft:tropics"
    },
    "behaviors": [
      {
        "type": "lt:common/waiting",
        "regions": {
          "spawn": "spawn"
        }
      }
    ]
  },
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:games/survive_the_tide/survive_the_tide_3",
    "dimension_type": "lt:raised_clouds"
  },
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "adventure",
      "join_late_with_role": "spectator",
      "backend_id": "lt:survive_the_tide_3",
      "statistics_key": "survive_the_tide"
    },
    {
      "type": "lt:survive_the_tide/3/map",
      "tide": 180
    },
    "lt:survive_the_tide/3/phases",
    "lt:survive_the_tide/mode/ffa",
    "lt:survive_the_tide/3/weather",
    "lt:survive_the_tide/common"
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/survive_the_tide_2_kevin_rtgame.json
{
  "name": {"translate": "ltminigames.minigame.survive_the_tide_2"},
  "subtitle": "Kevin & RTGame",

  "statistics_key": "survive_the_tide",
  "backend_id": "lt:survive_the_tide_2_teams",

  "minimum_participants": 3,
  "maximum_participants": 24,
  "waiting": {
    "map": {
      "type": "ltminigames:load_map",
      "load_from": "lt:waiting_lobby",
      "dimension_type": "tropicraft:tropics"
    },
    "behaviors": [
      {
        "type": "lt:common/waiting",
        "regions": {
          "spawn": "spawn"
        }
      },
      {
        "type": "ltminigames:setup_teams",
        "teams": [
          {
            "key": "the_duo",
            "name": "The Duo",
            "dye": "red",
            "text": "red",
            "assign": [
              "3e6835f1-7344-435a-9a23-c2f2441a002c",
              "dce7b3a1-6f05-41a6-91cd-71c34de5b801"
            ]
          },
          {
            "key": "the_viewers",
            "name": "The Viewers",
            "dye": "aqua",
            "text": "aqua"
          }
        ]
      }
    ]
  },
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:survive_the_tide_2"
  },
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "adventure",
      "join_as_role": "spectator"
    },
    "ltminigames:teams",
    {"type": "ltminigames:set_max_health", "max_health_by_team": {"the_viewers": 6.0}},
    "lt:survive_the_tide/stt2_map",
    "lt:survive_the_tide/stt2_phases",
    "lt:survive_the_tide/intro",
    "lt:survive_the_tide/ruleset",
    "lt:survive_the_tide/teams_win_logic",
    "lt:survive_the_tide/weather_stt2",
    "lt:survive_the_tide/stream_integrations",
    "lt:survive_the_tide/common"
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/speed_carb_golf.json
{
  "name": {
    "translate": "ltminigames.minigame.speed_carb_golf",
    "color": "dark_green",
    "extra": [
      " ",
      {
        "translate": "ltminigames.minigame.teams_2",
        "color": "gold"
      }
    ]
  },
  "minimum_participants": 1,
  "maximum_participants": 1000,
  "hide_from_list": false,
  "waiting": {
    "map": {
      "type": "ltminigames:load_map",
      "load_from": "lt:games/waiting_lobby",
      "dimension_type": "tropicraft:tropics"
    },
    "behaviors": [
      {
        "type": "lt:common/waiting",
        "regions": {
          "spawn": "spawn"
        }
      },
      "lt:teams/red_blue"
    ]
  },
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:games/speed_carb_golf"
  },
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "adventure",
      "join_late_with_role": "spectator",
      "allow_rejoin": true,
      "statistics_key": "speed_carb_golf"
    },
    "ltminigames:teams",
    "lt:speed_carb_golf/common"
  ]
}

=== LoveTropics/LTDatapack/data/lt/games/survive_the_tide_2_teams_3.json
{
  "name": {"translate": "ltminigames.minigame.survive_the_tide_2"},
  "subtitle": "3 Teams",
  "icon": "ltminigames:textures/gui/minigames/survive_the_tide/icon.png",

  "statistics_key": "survive_the_tide",
  "backend_id": "lt:survive_the_tide_2_teams",

  "minimum_participants": 3,
  "maximum_participants": 40,
  "waiting": {
    "map": {
      "type": "ltminigames:load_map",
      "load_from": "lt:waiting_lobby",
      "dimension_type": "tropicraft:tropics"
    },
    "behaviors": [
      {
        "type": "lt:common/waiting",
        "regions": {
          "spawn": "spawn"
        }
      },
      "lt:teams/red_blue_yellow"
    ]
  },
  "map": {
    "type": "ltminigames:load_map",
    "load_from": "lt:survive_the_tide_2"
  },
  "behaviors": [
    {
      "type": "lt:common/playing",
      "game_type": "adventure",
      "join_late_with_role": "spectator"
    },
    "ltminigames:teams",
    "lt:survive_the_tide/stt2_map",
    "lt:survive_the_tide/stt2_phases",
    "lt:survive_the_tide/intro",
    "lt:survive_the_tide/ruleset",
    "lt:survive_the_tide/teams_win_logic",
    "lt:survive_the_tide/teams_glow_members",
    "lt:survive_the_tide/weather_stt2",
    "lt:survive_the_tide/stream_integrations",
    "lt:survive_the_tide/common"
  ]
}
